In [11]:
import numpy as np
import scipy.linalg as la
from nb_general import to_edge_space, create_s_t
import networkx as nx
from sympy import *
from sklearn.preprocessing import normalize

In [12]:
# Create Graph
G = nx.Graph([[0,1],[1,2],[2,0]])

In [13]:
C = to_edge_space(G, graph=False)

In [14]:
# Find eigenvalues of C
vals, lvecs, rvecs = la.eig(C,left=True)

In [15]:
# Make some diagonal matrix
lambda_ = np.diag(vals)

In [16]:
la.solve(lvecs,np.eye(6))

array([[ 1.18989452,  1.18989452, -2.37978904,  1.18989452,  1.18989452,
        -2.37978904],
       [-0.83326685,  0.83326685, -0.83326685,  0.83326685,  0.83326685,
        -0.83326685],
       [ 0.40824829,  0.40824829,  0.40824829,  0.40824829,  0.40824829,
         0.40824829],
       [-0.04044011, -2.04044011,  2.08088023, -2.04044011, -0.04044011,
         2.08088023],
       [-0.46948948,  0.46948948,  0.93473753, -0.93473753, -1.38973907,
         1.38973907],
       [-0.32019242,  0.32019242, -1.15846448,  1.15846448, -0.05651694,
         0.05651694]])

In [17]:
lvecs@lambda_@rvecs

array([[-0.55227307+0.j, -0.21896793+0.j,  0.21896793+0.j,  0.44543762+0.j,
         0.36364513+0.j, -0.52866358+0.j],
       [-0.55227307+0.j, -0.21896793+0.j,  0.21896793+0.j,  0.44543762+0.j,
         0.36364513+0.j, -0.52866358+0.j],
       [-0.16042435+0.j, -0.36487741+0.j,  0.77312570+0.j,  0.16208641+0.j,
        -0.01037010+0.j, -0.27092865+0.j],
       [-0.16042435+0.j, -0.36487741+0.j,  0.77312570+0.j,  0.16208641+0.j,
        -0.01037010+0.j, -0.27092865+0.j],
       [-0.70151614+0.j, -0.41615465+0.j,  0.00790636+0.j,  0.68095904+0.j,
         0.55222998+0.j, -0.86727636+0.j],
       [-0.70151614+0.j, -0.41615465+0.j,  0.00790636+0.j,  0.68095904+0.j,
         0.55222998+0.j, -0.86727636+0.j]])

In [67]:
for i in range(10):
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]
    C = to_edge_space(G, graph=False)
    vals, lvecs, rvecs = la.eig(C,left=True)
    avals, alvecs, arvecs= la.eig(nx.adjacency_matrix(G).todense(),left=True)
    S, T = create_s_t(G)
    # Check for linear independence
    U, s, V = la.svd(S@arvecs)
    if len(s) == len(arvecs):
        print(f'Attempt {i+1}: Linearly Independent')
    else:
        print(f'Attempt {i+1}: Linearly Dependent')
# la.solve(vecs,np.eye(vecs.shape[0]))

Attempt 1: Linearly Independent
Attempt 2: Linearly Independent
Attempt 3: Linearly Independent
Attempt 4: Linearly Independent
Attempt 5: Linearly Independent
Attempt 6: Linearly Independent
Attempt 7: Linearly Independent
Attempt 8: Linearly Independent
Attempt 9: Linearly Independent
Attempt 10: Linearly Independent


In [18]:
S

S

In [30]:
avals, alvecs, arvecs= la.eig(nx.adjacency_matrix(G).todense(),left=True)

In [20]:
print(arvecs)
# print(rvecs)
print(avals,vals)

[[-0.81649658  0.57735027  0.19219669]
 [ 0.40824829  0.57735027 -0.7833358 ]
 [ 0.40824829  0.57735027  0.59113912]]
[-1.+0.j  2.+0.j -1.+0.j] [ -1.00000000e+00+0.j  -1.31838984e-16+0.j   2.00000000e+00+0.j
  -1.00000000e+00+0.j  -5.68050236e-16+0.j   2.81696547e-17+0.j]


In [31]:
S, T = create_s_t(G)

In [32]:
normalize(S@arvecs)

array([[ 0.22173834,  0.20679012, -0.27041438, ...,  0.10505747,
         0.21713144,  0.25576156],
       [ 0.26635184,  0.04886156, -0.55017361, ...,  0.18704667,
        -0.02123978,  0.05621306],
       [ 0.3448366 ,  0.10793961, -0.09499169, ...,  0.2038833 ,
        -0.04836071, -0.27118382],
       ..., 
       [ 0.13806061, -0.06106819, -0.1276344 , ..., -0.22466442,
        -0.20097604, -0.30088072],
       [ 0.38056196,  0.21086382,  0.14543639, ...,  0.24137162,
         0.05432137,  0.08962589],
       [ 0.3448366 ,  0.10793961, -0.09499169, ...,  0.2038833 ,
        -0.04836071, -0.27118382]])

In [48]:
C.sum(axis=0)

array([ 3.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  3.,  3.,  3.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  2.,  2.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  7.,  7.,  7.,  7.,
        7.,  7.,  7.,  1.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,
        2.,  6.,  6.,  6.,  6.,  6.,  6.,  3.,  3.,  3.,  5.,  5.,  5.,
        5.,  5.,  7.,  7.,  7.,  7.,  7.,  7.,  7.])

#### rvecs

$TS\hat{v}=\lambda\hat{v}$

$STS\hat{v}=\lambda S\hat{v}$

$STv=\lambda v$

$S_{ei}=\begin{cases}1&\text{if e\rightarrow i}\\0&\text{else}\end{cases}$

If $S$ is injective, then $S$ preserves linear independence.
$S$ is injective iff $S$ has full column rank (i.e. rank of $S$ is the number of columns).
Each row of $S$ has one entry.
Because of this, the columns cannot be combined into a linearly combination that equals the zero vector.
Thus, $S$ has full column rank and preserves linear independence.
So all the eigenvectors $Sv$ are linearly independent of one another.
All other eigenvectors are eigenvectors with eigenvalue 0.
These eigenvectors are basis elements of the eigenspace of eigenvalue 0 and thus are linearly independent.
For all $Sv$ not in the eigenbasis of eigenvalue 0, $Sv$ and the eigenvectors of the eigenspace are linearly independent.
If $Sv$ is in the basis of the eigenspace of 0, 

In [55]:
(S@arvecs).shape

(74, 19)

In [86]:
new = vals[vals < 1e-10]
len(new[new > -1e-10])


1410

In [73]:
S.sum(axis=1)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [87]:
test = nx.Graph([[1,2],[2,1]])

In [88]:
s, t = create_s_t(test)

In [93]:
la.eig(s@t)

(array([ 1.+0.j, -1.+0.j]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [95]:
s@t

array([[ 0.,  1.],
       [ 1.,  0.]])