In [18]:
import numpy as np
import scipy.linalg as la
from nb_general import to_edge_space, create_s_t
import networkx as nx
from sympy import *
from sklearn.preprocessing import normalize
from matplotlib import pyplot as plt

In [2]:
# Create Graph
G = nx.Graph([[0,1],[1,2],[2,0]])

In [3]:
C, tau = to_edge_space(G, graph=False, ret_tau=True)

In [4]:
S, T = create_s_t(G)

In [5]:
C@C.T

array([[ 2.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  2.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  2.],
       [ 0.,  2.,  0.,  2.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  2.]])

In [6]:
A = nx.adjacency_matrix(G).todense()

In [7]:
D = np.diag(A.sum(axis=1))

In [8]:
D

array([2], dtype=int64)

In [9]:
# Find eigenvalues of C
vals, lvecs, rvecs = la.eig(C,left=True)

In [10]:
# Make some diagonal matrix
lambda_ = np.diag(vals)

In [11]:
la.solve(lvecs,np.eye(6))

array([[ 1.18989452,  1.18989452, -2.37978904,  1.18989452,  1.18989452,
        -2.37978904],
       [-0.83326685,  0.83326685, -0.83326685,  0.83326685,  0.83326685,
        -0.83326685],
       [ 0.40824829,  0.40824829,  0.40824829,  0.40824829,  0.40824829,
         0.40824829],
       [-0.04044011, -2.04044011,  2.08088023, -2.04044011, -0.04044011,
         2.08088023],
       [-0.46948948,  0.46948948,  0.93473753, -0.93473753, -1.38973907,
         1.38973907],
       [-0.32019242,  0.32019242, -1.15846448,  1.15846448, -0.05651694,
         0.05651694]])

In [12]:
lvecs@lambda_@rvecs

array([[-0.55227307+0.j, -0.21896793+0.j,  0.21896793+0.j,  0.44543762+0.j,
         0.36364513+0.j, -0.52866358+0.j],
       [-0.55227307+0.j, -0.21896793+0.j,  0.21896793+0.j,  0.44543762+0.j,
         0.36364513+0.j, -0.52866358+0.j],
       [-0.16042435+0.j, -0.36487741+0.j,  0.77312570+0.j,  0.16208641+0.j,
        -0.01037010+0.j, -0.27092865+0.j],
       [-0.16042435+0.j, -0.36487741+0.j,  0.77312570+0.j,  0.16208641+0.j,
        -0.01037010+0.j, -0.27092865+0.j],
       [-0.70151614+0.j, -0.41615465+0.j,  0.00790636+0.j,  0.68095904+0.j,
         0.55222998+0.j, -0.86727636+0.j],
       [-0.70151614+0.j, -0.41615465+0.j,  0.00790636+0.j,  0.68095904+0.j,
         0.55222998+0.j, -0.86727636+0.j]])

In [52]:
for i in range(10):
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]
    C = to_edge_space(G, graph=False)
    vals, lvecs, rvecs = la.eig(C,left=True)
    avals, alvecs, arvecs= la.eig(nx.adjacency_matrix(G).todense(),left=True)
    S, T = create_s_t(G)
    # Check for linear independence
    U, s, V = la.svd(S@arvecs)
    print(la.det(C))
    if len(s) == len(arvecs):
        print(f'Attempt {i+1}: Linearly Independent')
    else:
        print(f'Attempt {i+1}: Linearly Dependent')
# la.solve(vecs,np.eye(vecs.shape[0]))

KeyboardInterrupt: 

In [47]:
# Create graph with 0 as eigenvalue in A
G = nx.Graph([[1,2],[1,4],[1,6],[1,8],[3,2],[3,4],[3,6],
              [3,8],[5,2],[5,4],[5,6],[5,8],[7,2],[7,4],
              [7,6],[7,8]])

In [48]:
# Get adjacency matrix
A = nx.adjacency_matrix(G).todense()

In [49]:
avals, alvecs, arvecs = la.eig(A,left=True)

In [50]:
# Take to edge space
C = to_edge_space(G, graph=False)

In [51]:
print(la.det(C))

0.0


In [44]:
U, s, V = la.svd(C.T-C)
vals, lvecs, rvecs = la.eig(C.T-C,left=True)
print(len(s),len(rvecs))

32 32


In [46]:
test = np.array([[1,1],[0,0]])
print(la.det(test))
U, s, V = la.svd(test)
vals, vecs = la.eig(test)
print(len(s),len(vecs))

0.0
2 2


#### rvecs

$TS\hat{v}=\lambda\hat{v}$

$STS\hat{v}=\lambda S\hat{v}$

$STv=\lambda v$

$S_{ei}=\begin{cases}1&\text{if e\rightarrow i}\\0&\text{else}\end{cases}$

If $S$ is injective, then $S$ preserves linear independence.
$S$ is injective iff $S$ has full column rank (i.e. rank of $S$ is the number of columns).
Each row of $S$ has one entry.
Because of this, the columns cannot be combined into a linearly combination that equals the zero vector.
Thus, $S$ has full column rank and preserves linear independence.
So all the eigenvectors $Sv$ are linearly independent of one another.
All other eigenvectors are eigenvectors with eigenvalue 0.
These eigenvectors are basis elements of the eigenspace of eigenvalue 0 and thus are linearly independent.
For all $Sv$ not in the eigenbasis of eigenvalue 0, $Sv$ and the eigenvectors of the eigenspace are linearly independent.
If $Sv$ is in the basis of the eigenspace of 0, 

In [55]:
(S@arvecs).shape

(74, 19)

In [86]:
new = vals[vals < 1e-10]
len(new[new > -1e-10])


1410

In [73]:
S.sum(axis=1)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [87]:
test = nx.Graph([[1,2],[2,1]])

In [88]:
s, t = create_s_t(test)

In [93]:
la.eig(s@t)

(array([ 1.+0.j, -1.+0.j]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [95]:
s@t

array([[ 0.,  1.],
       [ 1.,  0.]])