In [1]:
import numpy as np
import scipy.linalg as la
import scipy.sparse as sparse
import networkx as nx
from networkx.algorithms.connectivity import edge_connectivity, average_node_connectivity

In [2]:
# Make mock sparse matrix
C = sparse.random(5,5,.2)

In [3]:
la.eig(C.A)

(array([ 0.00000000+0.j,  0.30922519+0.j,  0.08929874+0.j,  0.00000000+0.j,
         0.00000000+0.j]),
 array([[  0.00000000e+000,   5.47392149e-001,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000],
        [  1.00000000e+000,   8.36876236e-001,   0.00000000e+000,
          -1.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   1.00000000e+000,
          -9.02671026e-291,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           1.10381028e-291,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   1.00000000e+000]]))

In [4]:
B = sparse.random(5,5,.1)

In [5]:
la.eig(B.A)

(array([ 0.00000000+0.j,  0.00000000+0.j,  0.00000000+0.j,  0.78208825+0.j,
         0.00000000+0.j]),
 array([[  0.00000000e+000,   2.12604026e-291,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   1.00000000e+000,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           1.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   1.00000000e+000],
        [  1.00000000e+000,  -1.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   0.00000000e+000]]))

In [6]:
B.A

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.78208825,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.23566914,  0.        ,  0.        ,  0.        ,  0.        ]])

In [7]:
S = np.vstack((np.eye(3),np.eye(3)))

In [8]:
S@S.T

array([[ 1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.]])

In [9]:
A = np.random.random((5,5))

In [10]:
A = A.round()

In [11]:
vals, vecs = la.eig(A)

In [12]:
u = vecs[:,1]

In [13]:
u = u.reshape((A.shape[0],1))

In [14]:
u@u.T

array([[ 0.04556998-0.j,  0.11930375-0.j,  0.04556998-0.j, -0.14746755+0.j,
        -0.07373377+0.j],
       [ 0.11930375-0.j,  0.31234128-0.j,  0.11930375-0.j, -0.38607505+0.j,
        -0.19303753+0.j],
       [ 0.04556998-0.j,  0.11930375-0.j,  0.04556998-0.j, -0.14746755+0.j,
        -0.07373377+0.j],
       [-0.14746755+0.j, -0.38607505+0.j, -0.14746755+0.j,  0.47721501+0.j,
         0.23860751+0.j],
       [-0.07373377+0.j, -0.19303753+0.j, -0.07373377+0.j,  0.23860751+0.j,
         0.11930375+0.j]])

In [15]:
vals, v_vecs = la.eig(A,left=True,right=False)

In [16]:
v = v_vecs[:,1]
v = v.reshape((A.shape[0],1))

In [17]:
v@u.T

array([[-0.05657758+0.j, -0.14812203+0.j, -0.05657758+0.j,  0.18308890+0.j,
         0.09154445+0.j],
       [-0.05657758+0.j, -0.14812203+0.j, -0.05657758+0.j,  0.18308890+0.j,
         0.09154445+0.j],
       [ 0.12651132-0.j,  0.33121094-0.j,  0.12651132-0.j, -0.40939923+0.j,
        -0.20469962+0.j],
       [ 0.03496687-0.j,  0.09154445-0.j,  0.03496687-0.j, -0.11315516+0.j,
        -0.05657758+0.j],
       [-0.14812203+0.j, -0.38778852+0.j, -0.14812203+0.j,  0.47933297+0.j,
         0.23966648+0.j]])

In [18]:
v@u.T

array([[-0.05657758+0.j, -0.14812203+0.j, -0.05657758+0.j,  0.18308890+0.j,
         0.09154445+0.j],
       [-0.05657758+0.j, -0.14812203+0.j, -0.05657758+0.j,  0.18308890+0.j,
         0.09154445+0.j],
       [ 0.12651132-0.j,  0.33121094-0.j,  0.12651132-0.j, -0.40939923+0.j,
        -0.20469962+0.j],
       [ 0.03496687-0.j,  0.09154445-0.j,  0.03496687-0.j, -0.11315516+0.j,
        -0.05657758+0.j],
       [-0.14812203+0.j, -0.38778852+0.j, -0.14812203+0.j,  0.47933297+0.j,
         0.23966648+0.j]])

In [19]:
u@v.T

array([[-0.05657758+0.j, -0.05657758+0.j,  0.12651132-0.j,  0.03496687-0.j,
        -0.14812203+0.j],
       [-0.14812203+0.j, -0.14812203+0.j,  0.33121094-0.j,  0.09154445-0.j,
        -0.38778852+0.j],
       [-0.05657758+0.j, -0.05657758+0.j,  0.12651132-0.j,  0.03496687-0.j,
        -0.14812203+0.j],
       [ 0.18308890+0.j,  0.18308890+0.j, -0.40939923+0.j, -0.11315516+0.j,
         0.47933297+0.j],
       [ 0.09154445+0.j,  0.09154445+0.j, -0.20469962+0.j, -0.05657758+0.j,
         0.23966648+0.j]])

# Look at change in u

In [20]:
def to_edge_space(G, B=False, graph=True):
    direct = G.to_directed()
    # Find S and T
    S = np.zeros((len(direct.edges),len(G.nodes)))
    T = np.zeros((len(G.nodes),len(direct.edges)))
    for i,a in enumerate(direct.edges):
        for j,b in enumerate(G.nodes):
#             print(a,b)
            if a[1] == b:
                S[i,j] = 1
#                 print('S Here')
            if a[0] == b:
#                 print('T Here')
                T[j,i] = 1
    # Create edge matrix
    if B:
        # Create tau
        tau = np.zeros((len(direct.edges),len(direct.edges)))
        for i,a in enumerate(direct.edges):
            for j,b in enumerate(direct.edges):
                if a[0]==b[1] and a[1]==b[0]:
                    tau[i][j] = 1
        if graph:
            return nx.Graph(S@T), nx.Graph(S@T-tau)
        return S@T, S@T - tau
    if graph:
        return nx.Graph(S@T)
    return S@T

In [21]:
# Create small graph
G = nx.Graph()
G.add_edges_from([[0,1],[1,2],[2,0]])

In [22]:
C, B = to_edge_space(G, B=True, graph=False)
print(C)
print(B)

[[ 0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]]


In [23]:
# Get eigenvectors and eigenvalues of C and B
cvals, cvecs = la.eig(C)
bvals, bvecs = la.eig(B)

In [24]:
# Find second eigenvecotr of C and B
u = cvecs[:,1]
u_hat = bvecs[:,1]

In [25]:
# Look for change in u
delta_u = u_hat - u

In [26]:
delta_u

array([ 0.98559856-0.j , -0.40824829-0.j ,  0.40824829-0.j ,
       -0.69692343-0.5j, -0.40824829-0.j ,  0.11957316+0.5j])

In [27]:
store = np.zeros((10,3))
for i in range(10):
    count = 0
    # Create big graph
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]

    C, B = to_edge_space(G, B=True, graph=False)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Find second eigenvecotr of C and B
    u = cvecs[:,1]
    u_hat = bvecs[:,1]

    # Look for change in u
    delta_u = u_hat - u
    
    # Calc tau
    tau = C - B
    # Store in array
    store[i,0] = abs(delta_u).max()
#     store[i,1] = np.sum(tau[tau==1])
#     store[i,2] = edge_connectivity(G)
#     store[i,3] = average_node_connectivity(G)
    store[i,1] = len(G.nodes)
    store[i,2] = len(G.edges)
    print(f'Attempt {i+1}:\n\t $\\delta$: {abs(delta_u).max()}\tBE: {len(G.edges)}\tN: {len(G.nodes)}')
# \tEC: {edge_connectivity(G)}\tAC: {average_node_connectivity(G)} \tE: {len(G.edges)}
#     if len(delta_u[abs(delta_u) > 1]) >= 1:
#         count += 1
# print(count)

Attempt 1:
	 $\delta$: 0.09225922841659466	BE: 704	N: 100
Attempt 2:
	 $\delta$: 0.008427745578954031	BE: 696	N: 100
Attempt 3:
	 $\delta$: 0.09970236658724638	BE: 698	N: 100
Attempt 4:
	 $\delta$: 0.11046649986150138	BE: 709	N: 100
Attempt 5:
	 $\delta$: 0.00840700053137889	BE: 727	N: 100
Attempt 6:
	 $\delta$: 0.0942004684276728	BE: 719	N: 100
Attempt 7:
	 $\delta$: 0.008330329829962447	BE: 711	N: 100
Attempt 8:
	 $\delta$: 0.007982651912212695	BE: 739	N: 100
Attempt 9:
	 $\delta$: 0.09425568346522892	BE: 712	N: 100
Attempt 10:
	 $\delta$: 0.09475855070612146	BE: 730	N: 100


In [28]:
store

array([[  9.22592284e-02,   1.00000000e+02,   7.04000000e+02],
       [  8.42774558e-03,   1.00000000e+02,   6.96000000e+02],
       [  9.97023666e-02,   1.00000000e+02,   6.98000000e+02],
       [  1.10466500e-01,   1.00000000e+02,   7.09000000e+02],
       [  8.40700053e-03,   1.00000000e+02,   7.27000000e+02],
       [  9.42004684e-02,   1.00000000e+02,   7.19000000e+02],
       [  8.33032983e-03,   1.00000000e+02,   7.11000000e+02],
       [  7.98265191e-03,   1.00000000e+02,   7.39000000e+02],
       [  9.42556835e-02,   1.00000000e+02,   7.12000000e+02],
       [  9.47585507e-02,   1.00000000e+02,   7.30000000e+02]])

In [29]:
for i in range(10):
    count = 0
    # Create big graph
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]

    C, B = to_edge_space(G, B=True, graph=False)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Find second eigenvecotr of C and B
    u = cvecs[:,0]
    u_hat = bvecs[:,0]

    # Look for change in u
    delta_u = u_hat - u
    
    print(f'Attempt {i+1}: {abs(delta_u).max()}')
#     if len(delta_u[delta_u > 0]) >= 1:
#         count += 1
# print(count)

Attempt 1: 0.07343740400362665
Attempt 2: 0.001536926050900769
Attempt 3: 0.0012823494735363867
Attempt 4: 0.08892090074515066
Attempt 5: 0.0011999930055844842
Attempt 6: 0.0013374913549137075
Attempt 7: 0.08188140667854939
Attempt 8: 0.0017096521682667615
Attempt 9: 0.0011447360782980975
Attempt 10: 0.0010588508705649535
