In [1]:
import numpy as np
import scipy.linalg as la
import scipy.sparse as sparse
import networkx as nx
from networkx.algorithms.connectivity import edge_connectivity, average_node_connectivity

In [2]:
# Make mock sparse matrix
C = sparse.random(5,5,.2)

In [3]:
la.eig(C.A)

(array([ 0.00000000+0.j,  0.75493123+0.j, -0.75493123+0.j,  0.38739153+0.j,
         0.00000000+0.j]),
 array([[  0.00000000e+000,   6.94039053e-001,   6.94039053e-001,
           0.00000000e+000,  -7.43183312e-291],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           1.00000000e+000,   0.00000000e+000],
        [  1.00000000e+000,   8.48380283e-002,  -8.48380283e-002,
           0.00000000e+000,   1.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   8.62906791e-275],
        [  0.00000000e+000,   7.14921186e-001,  -7.14921186e-001,
           0.00000000e+000,  -3.94472656e-275]]))

In [4]:
B = sparse.random(5,5,.1)

In [5]:
la.eig(B.A)

(array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]),
 array([[  1.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,  -1.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   2.63711084e-291,
           0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           1.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
           0.00000000e+000,   1.02141215e-291],
        [  0.00000000e+000,   1.00000000e+000,  -1.00000000e+000,
           0.00000000e+000,   0.00000000e+000]]))

In [6]:
B.A

array([[ 0.        ,  0.        ,  0.        ,  0.49053861,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.1899966 ,  0.        ,  0.        ,  0.        ]])

In [7]:
S = np.vstack((np.eye(3),np.eye(3)))

In [8]:
S@S.T

array([[ 1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.]])

In [9]:
A = np.random.random((5,5))

In [10]:
A = A.round()

In [11]:
vals, vecs = la.eig(A)

In [12]:
u = vecs[:,1]

In [13]:
u = u.reshape((A.shape[0],1))

In [14]:
u@u.T

array([[ 0.47449006+0.j        , -0.13982545+0.12576031j,
         0.10587522+0.16341605j,  0.10587522+0.16341605j,
        -0.24702697-0.27772536j],
       [-0.13982545+0.12576031j,  0.00787267-0.07411954j,
        -0.07451221-0.02009488j, -0.07451221-0.02009488j,
         0.14640451+0.01636891j],
       [ 0.10587522+0.16341605j, -0.07451221-0.02009488j,
        -0.03265662+0.0729276j , -0.03265662+0.0729276j ,
         0.04052929-0.14704713j],
       [ 0.10587522+0.16341605j, -0.07451221-0.02009488j,
        -0.03265662+0.0729276j , -0.03265662+0.0729276j ,
         0.04052929-0.14704713j],
       [-0.24702697-0.27772536j,  0.14640451+0.01636891j,
         0.04052929-0.14704713j,  0.04052929-0.14704713j,
        -0.03395024+0.28917636j]])

In [15]:
vals, v_vecs = la.eig(A,left=True,right=False)

In [16]:
v = v_vecs[:,1]
v = v.reshape((A.shape[0],1))

In [17]:
v@u.T

array([[-0.25945298 -1.66068550e-01j,  0.12047241 -1.98281834e-02j,
        -0.00069838 -1.26412183e-01j, -0.00069838 -1.26412183e-01j,
         0.03787316 +2.38319180e-01j],
       [ 0.37980677 +0.00000000e+00j, -0.11192364 +1.00665156e-01j,
         0.08474809 +1.30806789e-01j,  0.08474809 +1.30806789e-01j,
        -0.19773336 -2.22305963e-01j],
       [ 0.18937257 +9.60821654e-02j, -0.08127131 +2.18778441e-02j,
         0.00916456 +8.66598479e-02j,  0.00916456 +8.66598479e-02j,
        -0.04235216 -1.60864169e-01j],
       [ 0.12765295 -2.92292348e-01j,  0.03985256 +1.19967918e-01j,
         0.12915032 -2.12564536e-02j,  0.12915032 -2.12564536e-02j,
        -0.23754073 +7.74550104e-02j],
       [-0.19773336 +2.22305963e-01j, -0.00065146 -1.17918257e-01j,
        -0.12068414 -1.84958819e-02j, -0.12068414 -1.84958819e-02j,
         0.23306173 +1.67448520e-16j]])

In [18]:
v@u.T

array([[-0.25945298 -1.66068550e-01j,  0.12047241 -1.98281834e-02j,
        -0.00069838 -1.26412183e-01j, -0.00069838 -1.26412183e-01j,
         0.03787316 +2.38319180e-01j],
       [ 0.37980677 +0.00000000e+00j, -0.11192364 +1.00665156e-01j,
         0.08474809 +1.30806789e-01j,  0.08474809 +1.30806789e-01j,
        -0.19773336 -2.22305963e-01j],
       [ 0.18937257 +9.60821654e-02j, -0.08127131 +2.18778441e-02j,
         0.00916456 +8.66598479e-02j,  0.00916456 +8.66598479e-02j,
        -0.04235216 -1.60864169e-01j],
       [ 0.12765295 -2.92292348e-01j,  0.03985256 +1.19967918e-01j,
         0.12915032 -2.12564536e-02j,  0.12915032 -2.12564536e-02j,
        -0.23754073 +7.74550104e-02j],
       [-0.19773336 +2.22305963e-01j, -0.00065146 -1.17918257e-01j,
        -0.12068414 -1.84958819e-02j, -0.12068414 -1.84958819e-02j,
         0.23306173 +1.67448520e-16j]])

In [19]:
u@v.T

array([[-0.25945298 -1.66068550e-01j,  0.37980677 +0.00000000e+00j,
         0.18937257 +9.60821654e-02j,  0.12765295 -2.92292348e-01j,
        -0.19773336 +2.22305963e-01j],
       [ 0.12047241 -1.98281834e-02j, -0.11192364 +1.00665156e-01j,
        -0.08127131 +2.18778441e-02j,  0.03985256 +1.19967918e-01j,
        -0.00065146 -1.17918257e-01j],
       [-0.00069838 -1.26412183e-01j,  0.08474809 +1.30806789e-01j,
         0.00916456 +8.66598479e-02j,  0.12915032 -2.12564536e-02j,
        -0.12068414 -1.84958819e-02j],
       [-0.00069838 -1.26412183e-01j,  0.08474809 +1.30806789e-01j,
         0.00916456 +8.66598479e-02j,  0.12915032 -2.12564536e-02j,
        -0.12068414 -1.84958819e-02j],
       [ 0.03787316 +2.38319180e-01j, -0.19773336 -2.22305963e-01j,
        -0.04235216 -1.60864169e-01j, -0.23754073 +7.74550104e-02j,
         0.23306173 +1.63370022e-16j]])

# Look at change in u

In [31]:
def to_edge_space(G, B=False, graph=True, ST = True):
    direct = G.to_directed()
    # Find S and T
    S = np.zeros((len(direct.edges),len(G.nodes)))
    T = np.zeros((len(G.nodes),len(direct.edges)))
    for i,a in enumerate(direct.edges):
        for j,b in enumerate(G.nodes):
#             print(a,b)
            if a[1] == b:
                S[i,j] = 1
#                 print('S Here')
            if a[0] == b:
#                 print('T Here')
                T[j,i] = 1
    if ST:
        return S, T
    # Create edge matrix
    if B:
        # Create tau
        tau = np.zeros((len(direct.edges),len(direct.edges)))
        for i,a in enumerate(direct.edges):
            for j,b in enumerate(direct.edges):
                if a[0]==b[1] and a[1]==b[0]:
                    tau[i][j] = 1
        if graph:
            return nx.Graph(S@T), nx.Graph(S@T-tau)
        return S@T, S@T - tau
    if graph:
        return nx.Graph(S@T)
    return S@T

In [21]:
# Create small graph
G = nx.Graph()
G.add_edges_from([[0,1],[1,2],[2,0]])

In [22]:
C, B = to_edge_space(G, B=True, graph=False)
print(C)
print(B)

[[ 0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.]
 [ 0.  0.  1.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]]


In [23]:
# Get eigenvectors and eigenvalues of C and B
cvals, cvecs = la.eig(C)
bvals, bvecs = la.eig(B)

In [24]:
# Find second eigenvecotr of C and B
u = cvecs[:,1]
u_hat = bvecs[:,1]

In [25]:
# Look for change in u
delta_u = u_hat - u

In [26]:
delta_u

array([ 0.98559856-0.j , -0.40824829-0.j ,  0.40824829-0.j ,
       -0.69692343-0.5j, -0.40824829-0.j ,  0.11957316+0.5j])

In [27]:
store = np.zeros((10,3))
for i in range(10):
    count = 0
    # Create big graph
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]

    C, B = to_edge_space(G, B=True, graph=False)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Find second eigenvecotr of C and B
    u = cvecs[:,1]
    u_hat = bvecs[:,1]

    # Look for change in u
    delta_u = u_hat - u
    
    # Calc tau
    tau = C - B
    # Store in array
    store[i,0] = abs(delta_u).max()
#     store[i,1] = np.sum(tau[tau==1])
#     store[i,2] = edge_connectivity(G)
#     store[i,3] = average_node_connectivity(G)
    store[i,1] = len(G.nodes)
    store[i,2] = len(G.edges)
    print(f'Attempt {i+1}:\n\t $\\delta$: {abs(delta_u).max()}\tBE: {len(G.edges)}\tN: {len(G.nodes)}')
# \tEC: {edge_connectivity(G)}\tAC: {average_node_connectivity(G)} \tE: {len(G.edges)}
#     if len(delta_u[abs(delta_u) > 1]) >= 1:
#         count += 1
# print(count)

Attempt 1:
	 $\delta$: 0.09751736509425493	BE: 715	N: 100
Attempt 2:
	 $\delta$: 0.09639150694538148	BE: 746	N: 100
Attempt 3:
	 $\delta$: 0.007268524349309968	BE: 749	N: 100
Attempt 4:
	 $\delta$: 0.09868692710125124	BE: 734	N: 100
Attempt 5:
	 $\delta$: 0.006483578807953982	BE: 743	N: 100
Attempt 6:
	 $\delta$: 0.0954800537028662	BE: 736	N: 100
Attempt 7:
	 $\delta$: 0.006721882044351868	BE: 740	N: 100
Attempt 8:
	 $\delta$: 0.00664402578914992	BE: 750	N: 100
Attempt 9:
	 $\delta$: 0.007480087422171062	BE: 699	N: 100
Attempt 10:
	 $\delta$: 0.006414466325834065	BE: 762	N: 100


In [32]:
store

array([[  9.75173651e-02,   1.00000000e+02,   7.15000000e+02],
       [  9.63915069e-02,   1.00000000e+02,   7.46000000e+02],
       [  7.26852435e-03,   1.00000000e+02,   7.49000000e+02],
       [  9.86869271e-02,   1.00000000e+02,   7.34000000e+02],
       [  6.48357881e-03,   1.00000000e+02,   7.43000000e+02],
       [  9.54800537e-02,   1.00000000e+02,   7.36000000e+02],
       [  6.72188204e-03,   1.00000000e+02,   7.40000000e+02],
       [  6.64402579e-03,   1.00000000e+02,   7.50000000e+02],
       [  7.48008742e-03,   1.00000000e+02,   6.99000000e+02],
       [  6.41446633e-03,   1.00000000e+02,   7.62000000e+02]])

In [29]:
for i in range(10):
    count = 0
    # Create big graph
    G = nx.random_partition_graph([50,50],0.25,.05)
    F = list(nx.connected_component_subgraphs(G))
    G = F[0]

    C, B = to_edge_space(G, B=True, graph=False)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Get eigenvectors and eigenvalues of C and B
    cvals, cvecs = la.eig(C)
    bvals, bvecs = la.eig(B)

    # Find second eigenvecotr of C and B
    u = cvecs[:,0]
    u_hat = bvecs[:,0]

    # Look for change in u
    delta_u = u_hat - u
    
    print(f'Attempt {i+1}: {abs(delta_u).max()}')
#     if len(delta_u[delta_u > 0]) >= 1:
#         count += 1
# print(count)

Attempt 1: 0.0010224748790278425
Attempt 2: 0.0012463461101081888
Attempt 3: 0.0011753259151001914
Attempt 4: 0.0012081831336366953
Attempt 5: 0.08168319562635878
Attempt 6: 0.0018605820248411842
Attempt 7: 0.001205209348104962
Attempt 8: 0.0014991171089890482
Attempt 9: 0.0777789113657826
Attempt 10: 0.0011351902006327026


In [34]:
S, T = to_edge_space(G, ST=True)

In [36]:
la.eig(S)

ValueError: expected square matrix