In [1]:
import networkx as nx
import numpy as np
import numpy.linalg as la
import scipy as sp
from nb_general import to_edge_space
from nb_general import create_s_t
from matplotlib import pyplot as plt

In [88]:
# Create sample graph
G = nx.Graph([[1,2],[1,3],[2,4],[2,5],[3,4],[5,1],[5,4]])
# G = nx.Graph([[1,2],[2,3],[3,1]])

In [89]:
# Get adjacency matrix
A = nx.adjacency_matrix(G).todense()

In [90]:
D  = np.diag(list(dict(G.degree).values()))

In [91]:
# Create new matrices
first = np.zeros((2*len(G.nodes),2*len(G.nodes)))
second = np.zeros((2*len(G.nodes),2*len(G.nodes)))

In [92]:
first[:len(G.nodes),:len(G.nodes)] = A
first[:len(G.nodes),len(G.nodes):] = D

In [93]:
list(dict(G.degree).values())

[3, 3, 2, 3, 3]

In [94]:
second[len(G.nodes):,:len(G.nodes)] = np.eye(len(G.nodes))
second[:len(G.nodes),len(G.nodes):] = np.eye(len(G.nodes))

In [95]:
sim_b = first - second

In [96]:
sim_b

array([[ 0.,  1.,  1.,  0.,  1.,  2.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  1.,  0.,  2.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  2.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  2.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.]])

In [97]:
# Compare eigenvalues
first_vals, first_vecs = la.eig(first)
second_vals, second_vecs = la.eig(second)
sim_b_vals, sim_b_vecs = la.eig(sim_b)

In [98]:
first_vecs

array([[  4.55798558e-01,   5.24424725e-01,   7.07106781e-01,
          1.31249313e-01,   1.10844409e-16,   7.07106781e-01,
          6.04967328e-01,  -7.23843609e-01,  -7.07106781e-01,
          3.49390987e-01],
       [  4.91222449e-01,  -3.30095756e-01,  -1.67138850e-16,
         -3.86959038e-01,  -7.07106781e-01,  -1.67138850e-16,
         -3.61126695e-17,   1.57817623e-01,   1.67138850e-16,
         -5.98360343e-01],
       [  3.19212092e-01,  -4.81695962e-01,  -2.03590690e-17,
          8.16132735e-01,  -1.18680864e-16,  -4.45091804e-17,
          3.56316061e-01,  -3.15635246e-01,  -3.79104251e-18,
          5.98360343e-01],
       [  4.55798558e-01,   5.24424725e-01,  -7.07106781e-01,
          1.31249313e-01,   8.57281303e-17,  -7.07106781e-01,
         -6.04967328e-01,   5.66025986e-01,   7.07106781e-01,
         -3.49390987e-01],
       [  4.91222449e-01,  -3.30095756e-01,  -1.66976220e-16,
         -3.86959038e-01,   7.07106781e-01,  -1.66976220e-16,
         -3.56316061e-01

In [99]:
la.eig(A)[1]

matrix([[  4.55798558e-01,   5.24424725e-01,   7.07106781e-01,
           1.31249313e-01,   1.10844409e-16],
        [  4.91222449e-01,  -3.30095756e-01,  -1.67138850e-16,
          -3.86959038e-01,  -7.07106781e-01],
        [  3.19212092e-01,  -4.81695962e-01,  -2.03590690e-17,
           8.16132735e-01,  -1.18680864e-16],
        [  4.55798558e-01,   5.24424725e-01,  -7.07106781e-01,
           1.31249313e-01,   8.57281303e-17],
        [  4.91222449e-01,  -3.30095756e-01,  -1.66976220e-16,
          -3.86959038e-01,   7.07106781e-01]])

In [100]:
la.eig(D)[1]

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [101]:
first_vecs

array([[  4.55798558e-01,   5.24424725e-01,   7.07106781e-01,
          1.31249313e-01,   1.10844409e-16,   7.07106781e-01,
          6.04967328e-01,  -7.23843609e-01,  -7.07106781e-01,
          3.49390987e-01],
       [  4.91222449e-01,  -3.30095756e-01,  -1.67138850e-16,
         -3.86959038e-01,  -7.07106781e-01,  -1.67138850e-16,
         -3.61126695e-17,   1.57817623e-01,   1.67138850e-16,
         -5.98360343e-01],
       [  3.19212092e-01,  -4.81695962e-01,  -2.03590690e-17,
          8.16132735e-01,  -1.18680864e-16,  -4.45091804e-17,
          3.56316061e-01,  -3.15635246e-01,  -3.79104251e-18,
          5.98360343e-01],
       [  4.55798558e-01,   5.24424725e-01,  -7.07106781e-01,
          1.31249313e-01,   8.57281303e-17,  -7.07106781e-01,
         -6.04967328e-01,   5.66025986e-01,   7.07106781e-01,
         -3.49390987e-01],
       [  4.91222449e-01,  -3.30095756e-01,  -1.66976220e-16,
         -3.86959038e-01,   7.07106781e-01,  -1.66976220e-16,
         -3.56316061e-01

In [102]:
second_vecs

array([[ 0.70710678,  0.70710678,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.70710678,
         0.70710678,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.70710678,  0.70710678

In [103]:
sim_b_vecs[:,1]

array([-0.38675580+0.06687493j,  0.22955539-0.05006608j,
        0.45480855+0.j        , -0.38675580+0.06687493j,
        0.22955539-0.05006608j, -0.27581437-0.12734175j,
        0.16826535+0.06897317j,  0.28978838+0.19985659j,
       -0.27581437-0.12734175j,  0.16826535+0.06897317j])