In [1]:
import numpy as np
import scipy.linalg as la
import networkx as nx
import matplotlib.pyplot as plt
import nb_general as nb

In [3]:
G = nx.gnp_random_graph(15,.7)

In [4]:
ex_1 = nb.NBEigVals(G)

In [11]:
vec1 = np.array([-1 for i in range(ex_1.n)] + [1 for i in range(ex_1.n)])

In [18]:
K_prime = ex_1.K-np.outer(vec1,vec1)/len(vec1)

In [17]:
ex_1.mu_vals

array([ 9.41153261+0.j        ,  1.        +0.j        ,
       -1.96436729+2.21593996j, -1.96436729-2.21593996j,
       -1.40976863+2.54326684j, -1.40976863-2.54326684j,
       -1.35661064+2.74700434j, -1.35661064-2.74700434j,
        0.81146071+2.83259458j,  0.81146071-2.83259458j,
        0.68023323+2.77682379j,  0.68023323-2.77682379j,
        0.44560709+3.02718941j,  0.44560709-3.02718941j,
        0.42658068+2.90162249j,  0.42658068-2.90162249j,
       -0.83909818+2.9873932j , -0.83909818-2.9873932j ,
       -0.47883231+3.3163845j , -0.47883231-3.3163845j ,
       -0.66104083+3.07146642j, -0.66104083-3.07146642j,
       -0.48195019+2.95825249j, -0.48195019-2.95825249j,
        0.02211228+3.02588657j,  0.02211228-3.02588657j,
       -0.16539054+2.98649049j, -0.16539054-2.98649049j,
       -0.23470167+3.03921966j, -0.23470167-3.03921966j])

In [44]:
np.outer(vec1,vec1)[:,0]/30

array([ 0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
        0.03333333,  0.03333333,  0.03333333,  0.03333333,  0.03333333,
       -0.03333333, -0.03333333, -0.03333333, -0.03333333, -0.03333333,
       -0.03333333, -0.03333333, -0.03333333, -0.03333333, -0.03333333,
       -0.03333333, -0.03333333, -0.03333333, -0.03333333, -0.03333333])

In [45]:
vals, vecs = la.eig(ex_1.K)

In [47]:
D = np.diag(vals)

In [48]:
X = vecs
X_inv = la.inv(vecs)

In [51]:
np.allclose(ex_1.K,X@D@X_inv)
np.round(X@D@X_inv,10)

array([[-0.-0.j, -0.-0.j,  1.+0.j,  0.+0.j, -0.+0.j, -0.+0.j,  1.+0.j,
        -0.-0.j,  1.-0.j,  1.-0.j,  1.-0.j,  1.+0.j, -0.+0.j,  1.-0.j,
         1.+0.j,  7.+0.j,  0.+0.j,  0.+0.j, -0.-0.j, -0.-0.j,  0.-0.j,
        -0.-0.j,  0.-0.j, -0.+0.j, -0.+0.j, -0.-0.j, -0.-0.j, -0.+0.j,
        -0.+0.j, -0.-0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  1.-0.j,  1.-0.j,  0.+0.j,  1.+0.j,
         1.+0.j,  1.-0.j, -0.+0.j,  1.-0.j,  0.-0.j,  0.+0.j,  1.+0.j,
         1.-0.j, -0.+0.j,  8.-0.j, -0.+0.j,  0.+0.j,  0.-0.j, -0.+0.j,
         0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j,  0.-0.j, -0.-0.j,  0.+0.j,
         0.-0.j, -0.+0.j],
       [ 1.-0.j,  1.-0.j,  0.-0.j,  1.+0.j,  0.+0.j,  1.+0.j,  1.+0.j,
         0.-0.j,  0.-0.j,  1.-0.j,  1.-0.j,  1.+0.j,  1.+0.j,  1.-0.j,
         1.+0.j,  0.+0.j,  0.+0.j, 10.-0.j,  0.-0.j,  0.+0.j,  0.+0.j,
         0.-0.j,  0.-0.j,  0.+0.j, -0.+0.j,  0.-0.j,  0.-0.j, -0.-0.j,
         0.+0.j,  0.-0.j],
       [ 0.-0.j,  1.-0.j,  1.+0.j,  0.+0.j,  1.-0.j,  1.+0.j,  1.-0

In [61]:
X_prime = np.delete(X,1,1)
X_prime_inv = la.inv(X_prime)

ValueError: expected square matrix

In [60]:
D_prime = np.diag(np.delete(vals,1))

In [63]:
D_prime

array([[ 9.41153261+0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -1.96436729+2.21593996j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.  

In [70]:
D_prime = np.diag(np.array(list(np.delete(vals,1))+[1+0*1j]))

In [80]:
X_prime = np.hstack((X_prime,vec1.reshape(30,1)))

In [81]:
X_prime_inv = la.inv(X_prime)

In [83]:
np.allclose(X_prime@D_prime@X_prime_inv,ex_1.K)

True