In [1]:
import numpy as np
import scipy.linalg as la
import networkx as nx
import nb_general as nb
import matplotlib.pyplot as plt

### 4-Regular Graph on 5 vertices

In [2]:
g_reg = nx.random_regular_graph(4,5)

In [3]:
reg = nb.NBEigVals(g_reg)

### Non-regular graph on 5 vertices

In [4]:
g = nx.Graph([[1,2],[2,3],[3,4],[4,5],[5,1],[4,1]])

In [5]:
ex = nb.NBEigVals(g)

### Compare x(D-I)y

In [6]:
reg.x_matrix[:,0].T@(reg.D-reg.I)@reg.y_matrix[:,0]

(4.543812732716682e-16+0j)

In [7]:
ex.x_matrix[:,0].T@(ex.D-ex.I)@ex.y_matrix[:,0]

(-1.4944761038168275+0j)

In [8]:
reg.x_matrix[:,1]@(reg.D-reg.I)@reg.y_matrix[:,0]

(-3+0j)

In [9]:
ex.x_matrix[:,1].T@(ex.D-ex.I)@ex.y_matrix[:,0]

(1.1514371509001167e-15+0j)

In [10]:
ex.x_matrix[:,1]@ex.y_matrix[:,0]

(8.183702435125697e-16+0j)

In [11]:
reg.x_matrix[:,0]@(reg.D-reg.I)@reg.y_matrix[:,4]/(reg.x_matrix[:,0].T@reg.y_matrix[:,4])

(2.9999999999999996+0j)

In [12]:
ex.x_matrix[:,0].T@(ex.D-ex.I)@ex.y_matrix[:,4]/(ex.x_matrix[:,0].T@ex.y_matrix[:,4])

(-0.7026244283627033+3.6004580079246233j)

In [13]:
ex.mu_vals[4]

(-0.5598188977032159+0.9998961096870119j)

In [14]:
reg.mu_vals[4]

(-0.5000000000000006+1.6583123951776997j)

In [15]:
ex.A@np.outer(ex.x_matrix[:,0],ex.x_matrix[:,0])

array([[0.69670213, 0.47036511, 0.47036511, 0.69670213, 0.56158611],
       [0.47036511, 0.31755801, 0.31755801, 0.47036511, 0.37914412],
       [0.47036511, 0.31755801, 0.31755801, 0.47036511, 0.37914412],
       [0.69670213, 0.47036511, 0.47036511, 0.69670213, 0.56158611],
       [0.56158611, 0.37914412, 0.37914412, 0.56158611, 0.45267403]])

In [16]:
ex.lambda_vals[0]*ex.x_matrix[:,0]

array([-1.31478263+0.j, -0.88765034+0.j, -0.88765034+0.j, -1.31478263+0.j,
       -1.0597982 +0.j])

In [17]:
ex.A@ex.x_matrix[:,0]

array([-1.31478263, -0.88765034, -0.88765034, -1.31478263, -1.0597982 ])

Non-regular 5 vertices

In [31]:
(ex.x_matrix[:,0].T@ex.D-ex.x_matrix[:,0].T)/ex.x_matrix[:,0]

array([2., 1., 1., 2., 1.])

In [34]:
(ex.x_matrix[:,0].T@ex.D@ex.y_matrix[:,0])/(ex.x_matrix[:,0]@ex.y_matrix[:,0])

(2.505424797610528-0j)

In [62]:
2*np.sqrt(ex.x_matrix[:,0]@(ex.D-ex.I)@test)

(2.4539150740076785+0j)

In [63]:
ex.lambda_vals[0]

(2.4811943040920172+0j)

In [75]:
-1*ex.x_matrix[:,0]@(ex.D-ex.I)@ex.y_matrix[:,0]

(1.4944761038168275+0j)

In [43]:
np.max(ex.x_matrix[:,0])*np.max(ex.y_matrix[:,0])*(2*len(ex.G.edges())-ex.n)

(-1.1856116731352846+0j)

In [74]:
summed = 0
for i in range(ex.n):
    degree = np.diag(ex.D)[i]-1
    summed += degree*np.max(-1*ex.x_matrix[:,0])*np.max(test)
summed

(1.7689867916368498+0j)

In [58]:
np.sum([i-1 for i in np.diag(ex.D)])

7

In [77]:
np.min(np.diag(ex.D)-1)

1

In [100]:
test = ex.y_matrix[:,0]/(ex.x_matrix[:,1]@ex.y_matrix[:,0])

In [101]:
ex.x_matrix[:,1]@test

(0.9878612229326212+0j)

In [67]:
np.max(-1*ex.x_matrix[:,0])

0.5298990988806641

In [78]:
ex.check_all_vals(1e-8)


		--------------------1---------------------

mu: (1.424054220740945+0j)
	0 - Positive: False	Negative:True	x^Ty=(-0.9927271732131165+0j)
	1 - Positive: False	Negative:False	x^Ty=(8.183702435125697e-16+0j)
	2 - Positive: True	Negative:False	x^Ty=(0.0872377883263342+0j)
	3 - Positive: False	Negative:False	x^Ty=(-4.119493599215496e-16+0j)
	4 - Positive: False	Negative:True	x^Ty=(-0.08295979660187308+0j)

		--------------------2---------------------

mu: (1.0000000000000002+0j)
	0 - Positive: False	Negative:True	x^Ty=(0.984957964994089+0j)
	1 - Positive: False	Negative:False	x^Ty=(-5.965007270682884e-16+0j)
	2 - Positive: False	Negative:True	x^Ty=(-0.12202436843145514+0j)
	3 - Positive: False	Negative:False	x^Ty=(3.5665540915077003e-16+0j)
	4 - Positive: True	Negative:False	x^Ty=(0.12234320865339006+0j)

		--------------------3---------------------

mu: (-0.9566845695646844+0.6411996580570046j)
	0 - Positive: False	Negative:False	x^Ty=(3.2814112190825255e-16-3.1433841465458314e-16j)
	1 -

In [80]:
ex.formula(0,0)

((1.0571400833510696-0j), (1.4240542207409475-0j))

In [81]:
ex.mu_vals

array([ 1.42405422+0.j        ,  1.        +0.j        ,
       -0.95668457+0.64119966j, -0.95668457-0.64119966j,
       -0.5598189 +0.99989611j, -0.5598189 -0.99989611j,
       -0.04331543+1.22718564j, -0.04331543-1.22718564j,
        0.34779179+0.97392469j,  0.34779179-0.97392469j])

In [123]:
np.abs(ex.mu_vals[2])**2

1.3263823671355852

In [125]:
ex.lambda_vals[1]**2/2-(2*len(ex.G.edges())-ex.n)*np.abs(np.min(ex.x_matrix[:,1]))*np.abs(np.min(test))

(-0.07670775814703967-0j)

In [106]:
ex.x_matrix[:,1]

array([-5.00000000e-01,  5.00000000e-01, -5.00000000e-01,  5.00000000e-01,
        9.25490977e-17])

In [120]:
test = ex.y_matrix[:,2]/(ex.y_matrix[:,2]@ex.x_matrix[:,1])

In [121]:
test@ex.x_matrix[:,1]

(1+3.469446951953618e-18j)